var switches=[
["difficult", "simple"],
["abandon", "leave"],
["abandoned", "left"],
["abandoning", "leaving"],
["abandons", "leaves"],
["abate", "make less"],
["abated", "made less"],
["abates", "makes less"],
["abating", "making less"],
["abbreviate", "make shorter"],
["abbreviated", "made shorter"],
["abbreviating", "making shorter"],
["abbreviation", "short form"],
["abdicate", "give up"],
["abdicates", "gives up"],
["abdicating", "giving up"],
["abduct", "take away"],
["abducted", "taken away"],
["abducting", "taking away"],
["abducts", "takes away"],
["abhor", "hate"],
["abhorred", "hated"],
["abhorring", "hating"],
["abhors", "hates"],
["abnormal", "not normal"],
["abnormally", "not normally"],
["aboard", "on"],
["abode", "living place"],
["abolish", "end"],
["abolished", "ended"],
["abolishing", "ending"],
["abominable", "very bad"],
["abominably", "very badly"],
["abridge", "shorten"],
["abridged", "shortened"],
["abridgements", "shorter forms"],
["abridges", "shortens"],
["abridging", "shortening"],
["abridgment", "shorter form"],
["abroad", "in another country"],
["abrupt", "sudden"],
["abruptly", "suddenly"],
["absolute", "complete"],
["absolute", "complete"],
["absolutely", "completely"],
["absolutely", "certainly"],
["absolve", "make free from"],
["absolved", "made free from"],
["absorb", "take up"],
["absorbed", "taken up"],
["absorbent", "able to take"],
["absorbs", "takes up"],
["abstractly", "in thoughts"],
["absurd", "strange"],
["absurdity", "strange thing"],
["absurdly", "foolishly"],
["abuse", "hurt"],
["abused", "hurt"],
["abusive", "hurtful"],
["abysmally", "very badly"],
["academy", "school"],
["accelerate", "increase in speed"],
["accelerated", "increased in speed"],
["accelerates", "increases"],
["accelerating", "increasing in speed"],
["acceleration", "increase in speed"],
["accentuate", "stress"],
["accentuated", "stressed"],
["accentuating", "stressing"],
["accessible", "usable"],
["accommodating", "nice"],
["accommodation", "room"],
["accompanied", "was with"],
["accompanies", "is with"],
["accompany", "go with"],
["accompany", "come with"],
["accompanying", "going with"],
["accompanying", "coming with"],
["accomplice", "friend"],
["accomplish", "do"],
["accomplishes", "does"],
["accomplishing", "doing"],
["accord", "agreement"],
["accordance", "agreement"],
["accords", "agreements"],
["accost", "trouble"],
["accosted", "troubled"],
["accosting", "troubling"],
["accosts", "troubles"],
["accumulate", "group"],
["accumulated", "grouped"],
["accumulates", "groups"],
["accumulating", "getting"],
["accumulation", "group"],
["accuracy", "amount of error"],
["accurate", "TRUE"],
["accurately", "correctly"],
["accusation", "claim"],
["accusations", "claims"],
["accustomed", "used to"],
["ache", "pain"],
["ached", "hurt"],
["aches", "pains"],
["aching", "hurting"],
["acquire", "get"],
["acquired", "got"],
["acquires", "gets"],
["acquiring", "getting"],
["activate", "start"],
["activated", "started"],
["activating", "starting"],
["actual", "real"],
["actuality", "fact"],
["actually", "really"],
["acute", "sharp"],
["adage", "saying"],
["adamant", "sure"],
["adamantly", "strongly"],
["additionally", "also"],
["adept", "expert"],
["adeptly", "expertly"],
["adequate", "enough"],
["adherent", "strong"],
["adhesive", "glue"],
["adjacent", "nearest"],
["adjudicate", "judge"],
["adjudicated", "judged"],
["adjudicating", "judging"],
["adjudicator", "judge"],
["administered", "gave"],
["administers", "gives"],
["admiration", "respect"],
["admire", "respect"],
["admired", "respected"],
["admissible", "allowed"],
["admit", "say"],
["admitted", "said"],
["adolescent", "child"],
["adolescents", "children"],
["adorable", "cute"],
["adore", "love"],
["adored", "loved"],
["adoring", "loving"],
["adorn", "decorate"],
["adorned", "decorated"],
["adorning", "decorating"],
["adrift", "floating"],
["advancing", "moving forward"],
["advocated", "argued"],
["advocating", "arguing"],
["afar", "far away"],
["affable", "nice"],
["affable", "kind"],
["affection", "love"],
["affectionate", "loving"],
["affectionately", "lovingly"],
["affluent", "rich"],
["agonizing", "very hard"],
["agreeable", "nice"],
["aid", "help"],
["aint", "is not"],
["alarming", "surprising"],
["aleatoric", "random"],
["alleviate", "ease"],
["alleviated", "eased"],
["alleviating", "easing"],
["allocate", "give"],
["allocated", "gave"],
["allowing", "letting"],
["alongside", "beside"],
["ambiguous", "unclear"],
["amend", "change"],
["amiss", "wrong"],
["among", "with"],
["among", "with"],
["among", "with"],
["amputate", "remove"],
["amputated", "removed"],
["amputation", "removal"],
["amusing", "funny"],
["analogous", "similar"],
["announce", "say"],
["annual", "yearly"],
["appalled", "disgusted"],
["appalling", "disgusting"],
["apparatus", "machine"],
["appreciable", "large"],
["appreciative", "thankful"],
["apprehension", "worry"],
["apprehensive", "worried"],
["appropriate", "ok"],
["appropriated", "bought"],
["appropriating", "buying"],
["arose", "grew"],
["arouse", "excite"],
["aroused", "excited"],
["arrange", "prepare"],
["arranged", "prepared"],
["arrangements", "plans"],
["arrangements", "plans"],
["arrangements", "plans"],
["arranging", "preparing"],
["arrogance", "rudeness"],
["arrogant", "rude"],
["arrogantly", "rudely"],
["articulate", "say"],
["ascertain", "find"],
["ascertain", "learn"],
["ascertained", "found"],
["ascertaining", "finding"],
["aspects", "parts"],
["assassinate", "kill"],
["assassinated", "killed"],
["assassinating", "killing"],
["assemble", "build"],
["assembled", "built"],
["assembling", "building"],
["assist", "help"],
["assisted", "helped"],
["associate", "group"],
["associated", "grouped"],
["associating", "grouping"],
["astray", "wrong"],
["attempt", "try"],
["attempt", "try"],
["attempted", "tried"],
["attempting", "trying"],
["attempting", "trying"],
["attend", "go"],
["attended", "went to"],
["authentic", "real"],
["authentic", "real"],
["authorize", "let"],
["authorized", "let"],
["authorizing", "letting"],
["automobile", "car"],
["awful", "very bad"],
["awful", "terrible"],
["awfully", "terribly"],
["awry", "wrong"],
["banish", "ban"],
["banished", "banned"],
["barring", "ignoring"],
["based", "built"],
["bash", "hit"],
["beatific", "good"],
["began", "started"],
["begin", "start"],
["belated", "late"],
["belch", "burp"],
["belched", "burped"],
["belching", "burping"],
["bellicose", "mean"],
["bellicose", "mean"],
["belligerent", "mean"],
["belligerent", "mean"],
["belligerents", "fighters"],
["belligerents", "fighters"],
["bellow", "yell"],
["bellow", "yell"],
["belly", "stomach"],
["belongings", "things"],
["below", "under"],
["beneath", "under"],
["beneficent", "good"],
["beneficial", "good"],
["beneficial", "good"],
["benefits", "helps"],
["benevolent", "good"],
["bequeath", "give"],
["berate", "criticize"],
["berated", "criticized"],
["berating", "criticizing"],
["berserk", "crazy"],
["bestial", "animal-like"],
["bestow", "give"],
["betwixt", "between"],
["bewilder", "confuse"],
["bewildered", "confused"],
["bewildering", "confusing"],
["bicker", "argue"],
["bickered", "argued"],
["bickering", "argueing"],
["bidder", "offerer"],
["bide", "wait"],
["bids", "offers"],
["biennially", "every two years"],
["bifurcate", "split"],
["bifurcated", "split"],
["bifurcation", "split"],
["bilateral", "two-sided"],
["billiard", "pool-table"],
["bin", "box"],
["blameworthy", "bad"],
["blissful", "great"],
["bobbed", "dipped"],
["bobbing", "dipping"],
["bold", "strong"],
["boldly", "strongly"],
["bombastic", "loud"],
["bombastically", "loudly"],
["breach", "break"],
["breached", "broke"],
["briefed", "taught"],
["briefly", "quickly"],
["brink", "edge"],
["burglar", "robber"],
["burglary", "robbery"],
["burley", "strong"],
["burly", "strong"],
["bursted", "broke"],
["bursting", "exploding"],
["byproduct", "result"],
["calculate", "find"],
["cancel", "stop"],
["cancel", "stop"],
["canceled", "stopped"],
["canceling", "stopping"],
["cancelled", "stopped"],
["cancelling", "stopping"],
["capture", "get"],
["captured", "got"],
["capturing", "getting"],
["cardigan", "sweater"],
["carve", "cut"],
["carved", "cut"],
["carving", "cutting"],
["cease", "end"],
["ceased", "ended"],
["ceaseless", "endless"],
["challenging", "difficult"],
["chapter", "part"],
["chastise", "criticize"],
["chastising", "criticizing"],
["cheerful", "happy"],
["cheery", "happy"],
["cherish", "love"],
["cherished", "loved"],
["cherishing", "loving"],
["chesterfield", "couch"],
["chop", "cut"],
["chopped", "cut"],
["chopping", "making cuts"],
["choppy", "rough"],
["chuckle", "laugh"],
["chuckled", "laughed"],
["chuckling", "laughing"],
["circumstance", "situation"],
["circumstance", "situation"],
["circumstance", "situation"],
["circumvent", "get around"],
["circumvented", "got around"],
["circumventing", "getting around"],
["circumvents", "gets around"],
["civilizations", "societies"],
["clad", "clothed"],
["clamber", "climb"],
["clambering", "climbing"],
["clarifies", "clears"],
["clarify", "clear"],
["clarifying", "clearing"],
["clasp", "grip"],
["cleaver", "knife"],
["cleft", "crack"],
["cling", "hold"],
["clinging", "holding"],
["clique", "group"],
["clone", "copy"],
["coalesce", "form"],
["coalesced", "formed"],
["coalescing", "forming"],
["cobbler", "shoe maker"],
["coerce", "force"],
["coined", "created"],
["collaborate", "work together"],
["collate", "organize"],
["collide", "hit"],
["collided", "hit"],
["collides", "hits"],
["colliding", "hitting"],
["colloquial", "everyday"],
["colossal", "big"],
["combining", "mixing"],
["comforter", "blanket"],
["comfy", "comfortable"],
["comical", "funny"],
["commence", "start"],
["commitment", "promise"],
["common", "normal"],
["commonly", "normally"],
["communal", "group"],
["commute", "travel"],
["commute", "travel"],
["commuted", "traveled"],
["commuted", "traveled"],
["commuter", "traveler"],
["commuter", "traveler"],
["commuting", "traveling"],
["commuting", "traveling"],
["companion", "friend"],
["compel", "force"],
["compelled", "forced"],
["compelling", "strong"],
["compilation", "collection"],
["complaisant", "nice"],
["compliance", "agreement"],
["compliant", "agreeable"],
["complimentary", "free"],
["comply", "agree"],
["component", "part"],
["components", "parts"],
["compose", "make"],
["compose", "make"],
["composed", "made"],
["composed", "made"],
["composing", "making"],
["comprehend", "understand"],
["comprehension", "understanding"],
["comprehensive", "complete"],
["compressed", "squeezed"],
["compressing", "squeezing"],
["comprised", "made"],
["compulsory", "necessary"],
["concatenate", "join"],
["conceal", "hide"],
["conceal", "hide"],
["concealed", "hidden"],
["concealed", "hid"],
["concealing", "hiding"],
["concealing", "hiding"],
["conception", "understanding"],
["concern", "worry"],
["concerned", "worried"],
["concerning", "about"],
["concoct", "make"],
["concocted", "made"],
["concocting", "creating"],
["concurrent", "simultaneous"],
["condone", "support"],
["condoned", "supported"],
["condoning", "supporting"],
["confidential", "secret"],
["confidentiality", "secretly"],
["confiscate", "take"],
["confiscated", "taken"],
["confiscating", "taking"],
["conform", "agree"],
["conforming", "aggreeing"],
["congeal", "solidify"],
["congealed", "solidified"],
["congealing", "solidifying"],
["conglomeration", "mass"],
["conglomeration", "organization"],
["congregate", "come together"],
["consensus", "general agreement"],
["consensus", "agreement"],
["consenting", "agreeing"],
["consequence", "effect"],
["consider", "think about"],
["considerable", "big"],
["considerable", "much"],
["considerably", "very"],
["considerate", "thoughtful"],
["considerate", "nice"],
["consideration", "thought"],
["consise", "neat"],
["constituent", "inner"],
["construct", "make"],
["construct", "build"],
["constructed", "made"],
["constructed", "built"],
["constructing", "making"],
["constructing", "building"],
["construction", "building"],
["constructive", "helping"],
["consume", "eat"],
["containing", "having"],
["contains", "has"],
["contains", "has"],
["contemporary", "recent"],
["contented", "happy"],
["continually", "constantly"],
["continuous", "unbroken"],
["contour", "outline"],
["contra", "against"],
["contraption", "machine"],
["contributed", "gave"],
["contributing", "giving"],
["contributor", "giver"],
["conventional", "normal"],
["conventionally", "normally"],
["converge", "come together"],
["converged", "came together"],
["converging", "coming together"],
["conversion", "change"],
["conversion", "change"],
["conversion", "change"],
["converted", "changed"],
["converted", "changed"],
["converted", "changed"],
["converted", "changed"],
["converting", "changing"],
["converting", "changing"],
["convocated", "graduated"],
["convocation", "graduation"],
["cools", "gets colder"],
["cop", "police officer"],
["copious", "large"],
["cordial", "nice"],
["corporate", "business"],
["corpse", "dead body"],
["corpses", "dead bodies"],
["corpulent", "fat"],
["corrected", "fixed"],
["corridor", "hall"],
["corridor", "hall"],
["costly", "expensive"],
["couldâve", "could have"],
["couldn't", "could not"],
["counterfactual", "wrong"],
["counterfeit", "fake"],
["courteous", "polite"],
["courteous", "nice"],
["courteous", "nice"],
["courteously", "politely"],
["covenant", "promise"],
["cozy", "comfortable"],
["crabby", "rude"],
["cracked in", "fixing"],
["crafted", "made"],
["crafted", "made"],
["crafting", "making"],
["crafting", "making"],
["crafty", "smart"],
["crashed", "smashed"],
["crashing", "smashing"],
["crass", "rude"],
["crave", "want"],
["craved", "wanted"],
["craving", "wanting"],
["created", "made"],
["creating", "making"],
["crowded", "filled"],
["crucial", "important"],
["crucial", "very important"],
["crucial", "important"],
["crucially", "importantly"],
["crucially", "importantly"],
["cruel", "mean"],
["cruel", "mean"],
["cruised", "drove"],
["cruising", "driving"],
["crumple", "crush"],
["cumbersome", "difficult"],
["currency", "money"],
["cursory", "quick"],
["curt", "short"],
["customary", "normal"],
["cyber", "internet"],
["cyberspace", "internet"],
["cycle", "circle"],
["cycled", "circled"],
["dagger", "knife"],
["dagger", "knife"],
["dainty", "delicate"],
["damnable", "bad"],
["dandy", "nice"],
["dangle", "hang"],
["dangled", "hanging"],
["dangling", "hanging"],
["dazzle", "impress"],
["dazzled", "impressed"],
["debris", "broken parts"],
["decade", "ten years"],
["decades", "tens of years"],
["deceased", "dead"],
["deciding", "choosing"],
["declaration", "statement"],
["declarations", "statements"],
["decompose", "breakdown"],
["decomposing", "breaking down"],
["decoy", "fake"],
["decreased", "lowered"],
["decreases", "lowers"],
["decreasing", "lowering"],
["decreasing", "lowering"],
["decrepit", "broken"],
["deduct", "remove"],
["deduct", "take away"],
["deducted", "removed"],
["deducting", "taking away"],
["deducting", "removing"],
["deem", "declare"],
["deemed", "declared"],
["defective", "bad"],
["deference", "respect"],
["deference", "respect"],
["deferential", "nice"],
["defiled", "dirtied"],
["definite", "sure"],
["degenerated", "broke down"],
["degenerating", "breaking"],
["deliberately", "purposely"],
["delicate", "special"],
["delighted", "happy"],
["delighted", "nice"],
["demeanor", "behavior"],
["demeanour", "behaviour"],
["demolish", "destroy"],
["demolish", "destroy"],
["demolished", "destroyed"],
["demolished", "destroyed"],
["demolishes", "destroys"],
["demolishing", "destroying"],
["demolishing", "destroying"],
["demonstrate", "show"],
["demonstrated", "shown"],
["demonstrating", "showing"],
["dense", "full"],
["depart", "leave"],
["departing", "leaving"],
["depict", "show"],
["depicted", "shown"],
["depicting", "showing"],
["deplorable", "terrible"],
["deplorable", "terrible"],
["depressed", "sad"],
["depression", "sadness"],
["deride", "make fun of"],
["derision", "disrespect"],
["derisively", "meanly"],
["derogatory", "mean"],
["desire", "want"],
["desired", "wanted"],
["desiring", "wanting"],
["despair", "worry"],
["despairing", "worrying"],
["despicable", "terrible"],
["despicable", "terrible"],
["despicable", "disgusting"],
["deteriorate", "break"],
["detestable", "terrible"],
["detrimental", "bad"],
["device", "tool"],
["devilish", "very bad"],
["devise", "make"],
["devised", "made"],
["devising", "making"],
["devising", "making"],
["devotion", "respect"],
["devout", "serious"],
["diminish", "lessen"],
["diminished", "lowered"],
["diminishing", "lessening"],
["dire", "bad"],
["disastrous", "and very bad"],
["discard", "drop"],
["disclose", "tell"],
["disclose", "tell"],
["disclosed", "told"],
["disclosing", "telling"],
["discontinue", "stop"],
["discontinued", "stopped"],
["discretion", "decision"],
["discuss", "talk about"],
["discussed", "talked about"],
["discusses", "talks about"],
["disembark", "leave"],
["disembarked", "left"],
["disembarking", "leaving"],
["disgraceful", "bad"],
["disgusting", "terrible"],
["dismal", "sad"],
["disparaged", "insulted"],
["disparagement", "insult"],
["disparaging", "insulting"],
["dispiriting", "sad"],
["display", "show"],
["displayed", "showed"],
["displaying", "showing"],
["disregarded", "ignored"],
["disregarding", "ignoring"],
["dissemination", "sharing"],
["distinguish", "separate"],
["distinguishing", "separating"],
["donate", "give"],
["donated", "gave"],
["donating", "giving"],
["drastic", "extreme"],
["drastic", "dramatic"],
["drastically", "dramatically"],
["dread", "fear"],
["dreaded", "feared"],
["dreadful", "terrible"],
["dreadful", "terrible"],
["dreading", "fearing"],
["dreary", "unhappy"],
["duration", "length"],
["duty", "job"],
["duvet", "blanket"],
["eager", "excited"],
["edit", "change"],
["educating", "teaching"],
["eject", "remove"],
["ejected", "removed"],
["ejecting", "removing"],
["elated", "excited"],
["elegant", "nice"],
["elegantly", "nicely"],
["elemental", "basic"],
["elementary", "basic"],
["elementary", "basic"],
["eliminate", "remove"],
["eliminated", "removed"],
["eliminating", "removing"],
["elimination", "removal"],
["eliminator", "remover"],
["elongate", "stretch"],
["elongated", "stretched"],
["elongating", "stretching"],
["eloquent", "smooth"],
["eloquently", "smoothly"],
["emmigrate", "move"],
["empathic", "strong"],
["emphatically", "heavily"],
["employee", "worker"],
["enable", "let"],
["enabled", "let"],
["enabling", "letting"],
["enigma", "mystery"],
["ennui", "boredom"],
["enormous", "very big"],
["enrich", "improve"],
["enriched", "improved"],
["enthusiasm", "excitement"],
["enthusiastic", "excited"],
["entire", "whole"],
["entirely", "very"],
["entirely", "completely"],
["entrenched", "stuck"],
["envisage", "see"],
["equipped", "prepared"],
["eradicate", "remove"],
["eradicated", "removed"],
["eradicating", "removing"],
["escalate", "increase"],
["escalated", "increased"],
["escalating", "growing"],
["establish", "make"],
["established", "made"],
["establishing", "making"],
["esteem", "respect"],
["estimate", "guess"],
["estimated", "guessed"],
["evacuate", "empty"],
["evacuated", "emptied"],
["evacuating", "leaving"],
["evade", "avoid"],
["evening", "night"],
["exasperate", "tire"],
["exasperated", "tired"],
["exasperating", "tiring"],
["exceed", "pass"],
["exceeds", "passes"],
["excellence", "greatness"],
["excellent", "great"],
["excellent", "very good"],
["exceptionally", "very"],
["exchanged", "traded"],
["exchanged", "traded"],
["exchanging", "trading"],
["exchanging", "trading"],
["exclude", "leave out"],
["excluded", "left out"],
["excludes", "leaves out"],
["excluding", "leaving out"],
["exclusively", "only"],
["excrement", "poo"],
["excursion", "trip"],
["exemplary", "excellent"],
["exemplary", "great"],
["exemplary", "great"],
["exhausted", "very tired"],
["exhausting", "very tiring"],
["expand", "grow"],
["expanded", "grew"],
["expanding", "growing"],
["expressed", "said"],
["expressing", "saying"],
["exquisite", "very nice"],
["extend", "grow"],
["extensive", "big"],
["extent", "amount"],
["extinguish", "stop"],
["extinguished", "stopped"],
["fabricate", "make up"],
["fabricated", "made up"],
["fabricates", "makes up"],
["fabrication", "fiction"],
["facetiously", "jokingly"],
["facilitate", "help"],
["facilitated", "helped"],
["facilitating", "helping"],
["failing to have", "organizing"],
["fallacious", "wrong"],
["fancy", "special"],
["fantastic", "amazing"],
["fantastically", "amazingly"],
["fare", "price"],
["fared", "did"],
["faring", "doing"],
["fascinate", "interest"],
["fascinating", "interesting"],
["fasten", "lock"],
["fathom", "understand"],
["fatigued", "tired"],
["fatiguing", "tiring"],
["faulty", "broken"],
["favored", "liked"],
["favoring", "liking"],
["favourable", "good"],
["favoured", "liked"],
["favouring", "liking"],
["feeble", "weak"],
["fend", "fight"],
["fended", "fought"],
["fending", "fighting"],
["festive", "happy"],
["fevered", "excited"],
["fiendish", "bad"],
["final", "last"],
["financed", "paid for"],
["fixated", "obsessed"],
["fixation", "obsession"],
["flourish", "grow"],
["flourishing", "growing"],
["folks", "people"],
["fooled", "tricked"],
["fooling", "tricking"],
["forging", "making"],
["forked", "split"],
["forking", "splitting"],
["formal", "nice"],
["formal", "important"],
["formulate", "make"],
["formulated", "made"],
["formulating", "making"],
["fortunately", "luckily"],
["foundational", "basic"],
["frankly", "basically"],
["frantic", "excited"],
["frantic", "crazy"],
["frantically", "almost"],
["fraternal", "brotherly"],
["fraternity", "club"],
["fraudulent", "fake"],
["frenetic", "excited"],
["frenzied", "excited"],
["frenzied", "crazy"],
["frequently", "often"],
["frolic", "play"],
["frontier", "edge"],
["functioning", "working"],
["fundamental", "basic"],
["funded", "paid for"],
["funding", "money"],
["funds", "money"],
["furious", "very angry"],
["furiously", "violently"],
["furnace", "heater"],
["fury", "violence"],
["futile", "useless"],
["gabbed", "talked"],
["gabbing", "talking"],
["gal", "girl"],
["gal", "girl"],
["gamble", "bet"],
["gambled", "bet"],
["garment", "clothing"],
["gaze", "look"],
["gazed", "looked"],
["gazing", "looking"],
["generate", "make"],
["generated", "made"],
["generating", "making"],
["genial", "warm of heart"],
["genteel", "nice"],
["gentle", "careful"],
["gently", "carefully"],
["genuine", "real"],
["genuinely", "truly"],
["get-go", "beginning"],
["giddy", "excited"],
["gigantic", "very big"],
["gigantic", "very big"],
["giggle", "laugh"],
["giggled", "laughed"],
["giggling", "laughing"],
["glad", "happy"],
["glean", "take"],
["gleaned", "taken"],
["glimpse", "quick look"],
["glitch", "problem"],
["glitches", "problems"],
["gloomy", "sad"],
["glum", "sad"],
["gonna", "going to"],
["gracefully", "nicely"],
["gracious", "thankful"],
["gradual", "slow"],
["gradual", "slow"],
["gradually", "slowly"],
["gradually", "slowly"],
["granting", "giving"],
["grateful", "thankful"],
["gratis", "free"],
["grievance", "complaint"],
["grievous", "terrible"],
["grim", "bad"],
["grin", "smile"],
["grinned", "smiled"],
["grinning", "smiling"],
["grip", "hold"],
["groceries", "food"],
["grubby", "dirty"],
["gruesome", "terrible"],
["guffaw", "laugh"],
["guffawed", "laughed"],
["guided", "led"],
["guided", "led"],
["gullet", "throat"],
["gusto", "great pleasure"],
["guy", "man"],
["guys", "men"],
["halt", "stop"],
["halted", "stopped"],
["halting", "stopping"],
["hands-down", "definitely"],
["hardiest", "strongest"],
["hardly", "barely"],
["hardy", "strong"],
["harm", "trouble"],
["harmed", "hurt"],
["harming", "hurting"],
["hath", "has"],
["haute", "high"],
["havoc", "chaos"],
["haywire", "crazy"],
["hazard", "danger"],
["hazardous", "dangerous"],
["heartless", "unkind"],
["heed", "attention"],
["hefty", "large"],
["hefty", "strong"],
["heinous", "terrible"],
["henceforth", "from now on"],
["henceforth", "from now on"],
["hideous", "terrible"],
["hideously", "terriblly"],
["highly", "very"],
["hike", "walk"],
["hiked", "walked"],
["hiking", "walking"],
["hitherto", "untill now"],
["hitherto", "until now"],
["hobbies", "interests"],
["hobby", "interest"],
["hoisted", "lifted"],
["hoisting", "lifting"],
["honor", "respect"],
["honored", "respected"],
["honoured", "respected"],
["horrendous", "terrible"],
["horrendously", "terribly"],
["horrible", "terrible"],
["horrid", "terrible"],
["horrific", "terrible"],
["horrified", "terrified"],
["horrifying", "terrible"],
["hound", "dog"],
["howâd", "how did"],
["howl", "yell"],
["humane", "kind"],
["humble", "simple"],
["humiliate", "embarrass"],
["humiliated", "embarrassed"],
["humor", "comedy"],
["humorous", "funny"],
["humour", "comedy"],
["hymn", "song"],
["hypothesis", "guess"],
["hypothesize", "guess"],
["i'll", "I will"],
["i'll", "I will"],
["i've", "I have"],
["illegality", "crime"],
["illuminated", "lit"],
["illustrating", "drawing"],
["illustration", "picture"],
["image", "picture"],
["immaculate", "perfect"],
["immediately", "very soon"],
["immense", "very big"],
["immigrate", "move"],
["immoral", "bad"],
["impart", "give"],
["impart", "teach"],
["imparted", "tought"],
["imparted", "gave"],
["imparting", "teaching"],
["imparting", "giving"],
["impeccable", "perfect"],
["impeccably", "perfectly"],
["impelled", "forced"],
["impending", "nearing"],
["improper", "bad"],
["impropriety", "crime"],
["inaccurate", "wrong"],
["inaccurate", "wrong"],
["inadequacies", "problems"],
["inane", "stupid"],
["inapropriate", "not ok"],
["inception", "beginning"],
["incoherent", "senseless"],
["incompetent", "stupid"],
["incorrect", "wrong"],
["increase", "raise"],
["increasing", "raising"],
["indicate", "show"],
["indicate", "show"],
["indicated", "showed"],
["indicated", "showed"],
["indicating", "showing"],
["indicating", "showing"],
["industry", "business"],
["inebriated", "drunk"],
["inexpensive", "cheap"],
["inexpressible", "unsayable"],
["infant", "baby"],
["infants", "babies"],
["inferior", "poor"],
["infinitesimal", "very small"],
["inform", "tell"],
["inform", "tell"],
["informed", "told"],
["informing", "telling"],
["informing", "telling"],
["infuriate", "anger"],
["infuriated", "angry"],
["ingenious", "smart"],
["ingenious", "smart"],
["ingest", "eat"],
["ingested", "ate"],
["ingesting", "eating"],
["inhabit", "live in"],
["inhabit", "live in"],
["inhabited", "lived in"],
["inhabiting", "living in"],
["initial", "first"],
["initialisation", "preparation"],
["initialise", "prepare"],
["initialised", "prepared"],
["initialising", "preparing"],
["initialization", "preparation"],
["initialize", "prepare"],
["initialized", "prepared"],
["initializing", "preparing"],
["initially", "at first"],
["initiate", "start"],
["initiated", "started"],
["initiating", "starting"],
["inject", "put"],
["injure", "hurt"],
["injure", "hurt"],
["injured", "hurt"],
["injured", "hurt"],
["injuring", "hurting"],
["injuring", "hurting"],
["inquire", "ask"],
["inquired", "asked"],
["inquiring", "asking"],
["inquiry", "question"],
["insane", "crazy"],
["insanity", "craziness"],
["inscribe", "write"],
["inscribing", "writing"],
["inserted", "put"],
["inserting", "putting"],
["insinuated", "suggested"],
["insinuating", "suggesting"],
["inspire", "excite"],
["inspire", "excite"],
["inspired", "excited"],
["inspired", "excited"],
["inspiring", "exciting"],
["instigate", "excite"],
["instigated", "excited"],
["instruct", "teach"],
["instructed", "taught"],
["instructing", "teaching"],
["instructor", "teacher"],
["instrumentation", "tools"],
["insurgency", "rebellion"],
["insurgent", "rebel"],
["intact", "complete"],
["integer", "whole number"],
["intelligent", "smart"],
["intend", "plan"],
["intending", "planning"],
["intense", "very strong"],
["intensely", "strongly"],
["intensity", "strength"],
["interim", "temporary"],
["interlaced", "twisted"],
["interlacing", "twisting"],
["internals", "insides"],
["interrogate", "question"],
["interrogated", "questioned"],
["interrogating", "questioning"],
["interrogation", "questioning"],
["intersect", "cross"],
["intersected", "crossed"],
["intersecting", "crossing"],
["intersperse", "spread"],
["interspersed", "spread"],
["interspersing", "spreading"],
["intricate", "complex"],
["intrigued", "interested"],
["intriguing", "interesting"],
["introspective", "thoughtful"],
["inundate", "fill"],
["inundated", "filled"],
["invariably", "always"],
["invariably", "always"],
["invariably", "always"],
["invent", "create"],
["invent", "create"],
["invented", "created"],
["invented", "created"],
["inventing", "creating"],
["inventing", "creating"],
["inventor", "creator"],
["inventory", "list"],
["investigated", "studied"],
["invigorate", "strengthen"],
["irate", "angry"],
["irrelevant", "not useful"],
["irresolute", "uncertain"],
["irrespective", "independant"],
["irreverent", "not serious"],
["irrigate", "water"],
["irrigated", "water"],
["irrigating", "watering"],
["irrigation", "watering"],
["irritable", "annoyed"],
["isolate", "separate"],
["isolate", "separate"],
["isolated", "separated"],
["issued", "gave"],
["issued", "gave"],
["issuing", "giving"],
["issuing", "giving"],
["iterated", "repeated"],
["iteration", "time"],
["itinerary", "plan"],
["jabbed", "poked"],
["jackpot", "prize"],
["jaded", "tired"],
["jamboree", "party"],
["jargon", "idiom"],
["jaunt", "trip"],
["jaunty", "happy"],
["jeer", "make fun of"],
["jeering", "making fun of"],
["jeopardize", "risk"],
["jest", "make fun of"],
["jesting", "making fun of"],
["jiggle", "shake"],
["jiggled", "shook"],
["jiggling", "shaking"],
["jitter", "shake"],
["jittered", "shook"],
["jittering", "shaking"],
["jolly", "happy"],
["jot", "write"],
["joted", "wrote"],
["joting", "writing"],
["jotted", "wrote"],
["jotted", "wrote"],
["jovial", "happy"],
["joy", "happiness"],
["joyful", "happy"],
["joyful", "happy"],
["joyless", "sad"],
["joyous", "happy"],
["jubilant", "happy"],
["jubilation", "happiness"],
["jumbled", "mixed"],
["jumbling", "mixing"],
["jumbo", "large"],
["junction", "cross"],
["junk", "garbage"],
["juxtapose", "compare"],
["juxtapose", "compare"],
["juxtaposed", "compared"],
["juxtaposing", "comparing"],
["juxtaposition", "comparison"],
["kidding", "joking"],
["kidnap", "take"],
["kindly", "nicely"],
["knack", "skill"],
["knapsack", "backpack"],
["knickers", "shorts"],
["know-how", "knowledge"],
["knucklehead", "idiot"],
["kook", "crazy person"],
["kooky", "crazy"],
["labored", "worked"],
["laborer", "worker"],
["laborers", "workers"],
["laboring", "working"],
["laboured", "worked"],
["laboured", "worked"],
["labouring", "working"],
["laceration", "wound"],
["lacked", "didn't have"],
["lacked", "missed"],
["lacking", "missing"],
["lacking", "missing"],
["lackluster", "boring"],
["laden", "filled"],
["lager", "beer"],
["lagoon", "lake"],
["lame", "uncool"],
["lard", "fat"],
["large", "big"],
["large scale", "big"],
["largely", "mostly"],
["larger", "bigger"],
["largest", "biggest"],
["latch", "lock"],
["laudable", "good"],
["lavatory", "bathroom"],
["lavish", "rich"],
["leap", "jump"],
["leaped", "jumped"],
["leaping", "jumping"],
["leapt", "jumped"],
["learnt", "learned"],
["lecturer", "teacher"],
["legend", "story"],
["legible", "clear"],
["legislation", "law"],
["legitimate", "real"],
["lesion", "wound"],
["liability", "danger"],
["liable", "responsible"],
["liberate", "free"],
["liberated", "freed"],
["liberating", "freeing"],
["likelihood", "chance"],
["linkage", "connection"],
["linked", "connected"],
["linking", "connecting"],
["liquor", "alcohol"],
["listless", "weak"],
["listlessly", "weakly"],
["literally", "actually"],
["livelihood", "money"],
["livestock", "animals"],
["loathe", "hate"],
["locals", "people"],
["locate", "find"],
["locating", "finding"],
["locator", "finder"],
["logged", "recorded"],
["logging", "recording"],
["loner", "loser"],
["long winded", "wordy"],
["lovely", "very nice"],
["lugged", "pulled"],
["lugging", "pulling"],
["lukewarm", "warm"],
["lumped", "put"],
["lumping", "putting"],
["lunge", "reach"],
["lunged", "reached"],
["lunging", "reaching"],
["lush", "rich"],
["lust", "desire"],
["luxurious", "nice"],
["lynch", "kill"],
["lyrics", "words"],
["macro", "large"],
["madness", "craziness"],
["mailed", "sent"],
["mainly", "mostly"],
["maintain", "keep"],
["maintained", "kept"],
["maintaining", "keeping"],
["maintaining", "keeping"],
["majestic", "beautiful"],
["malady", "injury"],
["malefactor", "wrongdoer"],
["malfunction", "error"],
["malfunctioning", "breaking"],
["malice", "hate"],
["malignity", "hate"],
["mallet", "hammer"],
["mandatory", "necessary"],
["mane", "hair"],
["maneuver", "move"],
["maneuvered", "moved"],
["maneuvering", "moving"],
["mangle", "damage"],
["mangled", "broken"],
["mangling", "damaging"],
["manifestly", "clearly"],
["manifesto", "statement"],
["manner", "act"],
["mannerly", "respectful"],
["mansion", "large house"],
["manufacture", "make"],
["manufactured", "made"],
["manufactured", "made"],
["manufacturers", "makers"],
["manuscript", "book"],
["marched", "walked"],
["massive", "large"],
["massively", "largely"],
["materialize", "happen"],
["materialized", "happened"],
["materializing", "happening"],
["maternal", "motherly"],
["maternity", "pregnancy"],
["mathematics", "math"],
["meadow", "field"],
["medley", "mix"],
["melancholic", "sad"],
["melancholy", "sadness"],
["mellow", "soft"],
["memo", "note"],
["menace", "danger"],
["mentality", "thinking"],
["mention", "talk about"],
["mentioned", "talked about"],
["mentioning", "talking about"],
["merchandise", "products"],
["merely", "only"],
["merely", "only"],
["merry", "happy"],
["method", "way"],
["methodical", "careful"],
["metropolis", "city"],
["microscopic", "very small"],
["mid", "middle"],
["midway", "half way"],
["migraine", "headache"],
["migrate", "move"],
["migrate", "move"],
["migrate", "move"],
["migrated", "moved"],
["migrated", "moved"],
["migrating", "moving"],
["migrating", "moving"],
["mingled", "mixed"],
["miniature", "many"],
["miraculous", "amazing"],
["miraculous", "amazing"],
["misapprehension", "confusion"],
["miscellany", "things"],
["misconception", "confusion"],
["misconception", "misunderstanding"],
["misconduct", "crime"],
["misconstrued", "misunderstood"],
["misdeed", "crime"],
["misdemeanor", "crime"],
["misdemeanour", "crime"],
["miserable", "very sad"],
["misery", "sadness"],
["misfortunate", "unlucky"],
["misfortune", "bad luck"],
["mishap", "mistake"],
["misinterpret", "misunderstand"],
["misinterpreted", "misunderstood"],
["misinterpreting", "misunderstanding"],
["mistaken", "wrong"],
["mistaken", "wrong"],
["mistakenly", "wrongly"],
["mistook", "confused"],
["mixture", "mix"],
["mobilize", "prepare"],
["mobilized", "prepared"],
["mobilizing", "preparing"],
["mock", "make fun of"],
["mocked", "made fun of"],
["mocking", "making fun of"],
["modification", "change"],
["modified", "changed"],
["modifying", "changing"],
["moist", "wet"],
["moisture", "wetness"],
["momentarily", "quickly"],
["momentous", "important"],
["momentous", "important"],
["morsel", "bit"],
["motivate", "excite"],
["motivated", "excited"],
["motive", "reason"],
["motorway", "highway"],
["motto", "saying"],
["munchies", "snacks"],
["municipal", "city"],
["municipalities", "towns"],
["municipality", "town"],
["murdered", "killed"],
["murdered", "killed"],
["murderer", "killer"],
["murdering", "killing"],
["murdering", "killing"],
["murky", "dark"],
["muster", "get"],
["mustering", "getting"],
["mute", "silent"],
["mute", "silent"],
["muted", "silenced"],
["muted", "silenced"],
["mutilate", "destroy"],
["mutilated", "destroyed"],
["mutilating", "destroying"],
["muting", "silencing"],
["mutter", "say"],
["muttered", "said"],
["muttering", "saying"],
["mystified", "amazed"],
["mystify", "amaze"],
["mystifying", "amazing"],
["nab", "take"],
["nagged", "complained"],
["nagging", "complaining"],
["nah", "no"],
["namesake", "name"],
["narrative", "story"],
["narratives", "stories"],
["narrowly", "barely"],
["naught", "nothing"],
["nay", "no"],
["necessitate", "need"],
["necessitated", "needed"],
["necessitating", "needing"],
["nefarious", "very bad"],
["nefariously", "very wrongly"],
["neglect", "ignore"],
["neglectful", "careless"],
["neglectfully", "carelessly"],
["negligible", "unimportant"],
["negligible", "unimportant"],
["negotiate", "argue"],
["negotiation", "argument"],
["newcomer", "new person"],
["newcomers", "new people"],
["newfangled", "different"],
["nibble", "bite"],
["nibbled", "bit"],
["nibbling", "biting"],
["niche", "place"],
["nigh", "near"],
["nil", "nothing"],
["nimble", "quick"],
["ninetieth", "90th"],
["nip", "bite"],
["nipped", "bit"],
["nipping", "biting"],
["nominate", "suggest"],
["nominated", "suggested"],
["nominating", "suggesting"],
["non-compliant", "disagreeable"],
["nondescript", "normal"],
["nope", "no"],
["nosy", "rude"],
["notable", "important"],
["notably", "importantly"],
["noteworthy", "important"],
["notified", "tell"],
["notified", "told"],
["notified", "told"],
["notifies", "tells"],
["notify", "tell"],
["notifying", "telling"],
["notifying", "telling"],
["notion", "idea"],
["novels", "stories"],
["nowadays", "today"],
["numerous", "many"],
["obfuscated", "confusing"],
["objected", "disagreed"],
["objecting", "disagreeing"],
["objectives", "goals"],
["obtain", "get"],
["obtained", "got"],
["obvious", "clear"],
["obviously", "clearly"],
["occasion", "time"],
["odor", "smell"],
["ominous", "scary"],
["onset", "starting"],
["ophthalmologist", "eye-expert"],
["opportunity", "chance"],
["optimal", "best"],
["optimal", "best"],
["optimize", "improve"],
["optimum", "best"],
["opulent", "rich"],
["ordinarily", "normally"],
["ordinarily", "normally"],
["ordinary", "normal"],
["orifice", "hole"],
["originally", "first"],
["oust", "remove"],
["ousted", "removed"],
["ousting", "removing"],
["outdo", "beat"],
["outrage", "anger"],
["outraged", "angry"],
["outskirts", "edge"],
["outweigh", "weigh more than"],
["overdue", "late"],
["overjoyed", "very happy"],
["oversight", "mistake"],
["pact", "agreement"],
["pandemonium", "craziness"],
["paraphernalia", "things"],
["parodied", "made fun of"],
["parody", "make fun of"],
["partook", "took part"],
["paternal", "fatherly"],
["paternalistic", "fatherly"],
["paw", "foot"],
["paws", "feet"],
["peered", "looked"],
["peering", "looking"],
["pejorative", "mean"],
["pending", "waiting"],
["pensive", "thoughtful"],
["perceive", "see"],
["performance", "show"],
["perhaps", "maybe"],
["peril", "great danger"],
["perilous", "dangerous"],
["perils", "dangers"],
["periodically", "sometimes"],
["permitted", "let"],
["permitting", "letting"],
["persist", "continue"],
["persisted", "continued"],
["persisting", "continuing"],
["perspective", "view"],
["pertains", "matters"],
["pertinent", "important"],
["peruse", "look at"],
["perused", "looked at"],
["perusing", "looking at"],
["phenomenal", "great"],
["phenomenally", "very"],
["photo", "picture"],
["photos", "pictures"],
["physician", "doctor"],
["pic", "picture"],
["pieced", "put"],
["piecing", "putting"],
["pistol", "gun"],
["pivotal", "important"],
["placed", "put"],
["placed", "put"],
["placid", "quiet"],
["placidly", "quietly"],
["plagued", "troubled"],
["plausible", "possible"],
["plead", "beg"],
["pleaded", "begged"],
["pleasant", "nice"],
["pleasant", "good"],
["pleased", "happy"],
["pleasing", "good"],
["pleasing", "nice"],
["pleasurable", "good"],
["pleasurable", "nice"],
["plentiful", "full"],
["plenty", "lots"],
["ploy", "trick"],
["plucked", "took"],
["plugging", "putting"],
["plump", "round"],
["plunge", "fall"],
["plunged", "fell"],
["plunging", "falling"],
["plush", "rich"],
["ply", "layer"],
["polished", "cleaned"],
["polishing", "cleaning"],
["pompous", "rude"],
["pompous", "self-important"],
["pompously", "self-importantly"],
["ponder", "thought"],
["ponder", "give thought to"],
["pondered", "gave thought to"],
["pondering", "thinking about"],
["pondering", "giving thought to"],
["ponders", "gives thought to"],
["pony", "small horse"],
["pooch", "dog"],
["populace", "public"],
["portly", "fat"],
["possess", "have"],
["possessing", "having"],
["postponed", "delayed"],
["postponed", "delay"],
["postponing", "delaying"],
["posture", "body position"],
["potent", "strong"],
["potentially", "maybe"],
["potentially", "maybe"],
["pouch", "bag"],
["pouches", "bags"],
["poultry", "chicken"],
["powerful", "strong"],
["praising", "thanking"],
["preceded", "came before"],
["precise", "tight"],
["predict", "guess"],
["predicted", "guessed"],
["predicted", "guessed"],
["predicting", "guessing"],
["prediction", "guess"],
["prediction", "des"],
["predominately", "mostly"],
["prefer", "hope"],
["preferably", "hopefully"],
["preference", "choice"],
["preferences", "desires"],
["preluded", "came before"],
["preluding", "coming before"],
["premature", "early"],
["prematurely", "early"],
["prepare", "get ready"],
["prepared", "ready"],
["prepared", "ready"],
["preparing", "getting ready"],
["preparing", "getting  ready"],
["preserve", "keep"],
["preserved", "kept"],
["preserving", "keeping"],
["presumably", "probably"],
["presume", "assume"],
["presuming", "assuming"],
["presuppose", "assume"],
["presuppose", "assume"],
["presupposed", "assumed"],
["presupposing", "assuming"],
["presupposition", "assumption"],
["previous", "earlier"],
["previously", "earlier"],
["previously", "earlier"],
["primarily", "mostly"],
["primary", "first"],
["principle", "idea"],
["proceed", "go ahead"],
["proceed", "went"],
["proclaim", "say"],
["procure", "get"],
["procured", "got"],
["procures", "gets"],
["procuring", "getting"],
["produced", "made"],
["producing", "making"],
["producing", "making"],
["product", "thing"],
["products", "things"],
["profess", "claim"],
["professed", "claimed"],
["professing", "claiming"],
["professor", "teacher"],
["profoundly", "very"],
["project", "gas"],
["proliferation", "spreading"],
["prolific", "everywhere"],
["prominent", "major"],
["promptly", "quickly"],
["promptly", "quickly"],
["propel", "push"],
["propelled", "pushed"],
["propelling", "pushing"],
["proper", "respectful"],
["proper", "right"],
["proposition", "choice"],
["proprietor", "owner"],
["proprietors", "owners"],
["prosaic", "common"],
["prosper", "do well"],
["prospering", "doing well"],
["prosperous", "rich"],
["protocol", "rules"],
["psalm", "song"],
["psyched", "excited"],
["pun", "joke"],
["punch", "hit"],
["punching", "hitting"],
["puncture", "get in"],
["punctured", "entered"],
["puncturing", "getting in"],
["purchased", "bought"],
["purchasing", "buying"],
["purifies", "cleans"],
["purify", "clean"],
["purifying", "cleaning"],
["purport", "claim"],
["purported", "claimed"],
["purporting", "claiming"],
["purposes", "reasons"],
["pursue", "go after"],
["pursued", "went after"],
["pursues", "goes after"],
["pursuing", "going after"],
["putrid", "gross"],
["quaint", "nice"],
["quaintly", "nicely"],
["quantities", "amounts"],
["quantity", "number"],
["quantity", "amount"],
["quarrel", "fight"],
["quarreling", "fighting"],
["quarrelled", "font"],
["quarrelled", "font"],
["quarrelling", "fighting"],
["queries", "questions"],
["query", "question"],
["querying", "questing"],
["queue", "line"],
["quirky", "weird"],
["quite", "truly"],
["radiated", "spread"],
["radiating", "spreading"],
["radically", "greatly"],
["raffle", "ticket-competition"],
["raging", "angry"],
["rage", "anger"],
["rapidly", "quickly"],
["ravel", "twist"],
["raveled", "twisted"],
["raveling", "twisting"],
["raze", "burn"],
["razed", "burned"],
["razing", "burning"],
["readily", "quickly"],
["realistic", "real"],
["realistically", "really"],
["reap", "enjoy"],
["reaped", "enjoyed"],
["reasoned", "thought"],
["reasoning", "thinking"],
["rebels", "turn"],
["recapitulates", "repeat"],
["recapitulation", "repetition"],
["receive", "get"],
["received", "got"],
["receives", "gets"],
["receiving", "getting"],
["recent", "new"],
["reclined", "rested"],
["reclining", "rest"],
["reclining", "resting"],
["recognize", "remember"],
["recognized", "remembered"],
["recollect", "remember"],
["recollection", "memory"],
["reek", "smell"],
["reeked", "smelt"],
["reeking", "smelling"],
["refine", "improve"],
["reform", "change"],
["reformed", "changed"],
["reforming", "changing"],
["regain", "get back"],
["regained", "got back"],
["regaining", "getting back"],
["regiment", "plan"],
["region", "area"],
["regulation", "rule"],
["rehabilitate", "recover"],
["rehabilitation", "recovery"],
["rehearsal", "practice"],
["rehearse", "practice"],
["rehearsed", "practiced"],
["rehearsing", "practicing"],
["reigned", "ruled"],
["reigning", "ruling"],
["reignite", "restart"],
["reignited", "restarted"],
["reigniting", "restarting"],
["reimburse", "paid back"],
["reimbursed", "paid back"],
["reimbursing", "paying back"],
["reinforcement", "support"],
["reinforcing", "supporting"],
["reinstate", "put back"],
["reinstated", "put back"],
["reinstates", "puts back"],
["reinstating", "putting back"],
["reiterate", "repeat"],
["reiterated", "repeated"],
["reiterating", "repeating"],
["reiteration", "repetition"],
["rejoice", "celebrate"],
["rejoicing", "celebrating"],
["relaxed", "comfortable"],
["relocate", "move"],
["relocated", "moved"],
["remark", "statement"],
["remarkable", "amazing"],
["remarking", "saying"],
["remorse", "regret"],
["remorseful", "regretful"],
["remorsefully", "regretfully"],
["removed", "took away"],
["removes", "takes away"],
["removing", "taking away"],
["rendition", "version"],
["renounce", "give up"],
["renouncing", "giving up"],
["renovate", "change"],
["renovated", "changed"],
["renovating", "changing"],
["repair", "fix"],
["repaired", "fixed"],
["repaired", "fixed"],
["repairing", "fixing"],
["repairing", "fixing"],
["replenish", "refill"],
["replenished", "refilled"],
["replenishing", "refilling"],
["replied", "answered"],
["replied", "answered"],
["reply", "answer"],
["reporter", "writer"],
["reprehensible", "terrible"],
["reprimand", "criticize"],
["repugnant", "terrible"],
["repulsive", "terrible"],
["requested", "asked for"],
["requesting", "asking for"],
["require", "need"],
["required", "needed"],
["requiring", "needing"],
["requisite", "necessary"],
["rescue", "save"],
["rescue", "save"],
["rescued", "saved"],
["rescued", "saved"],
["rescuer", "saver"],
["rescuing", "saving"],
["rescuing", "saving"],
["researched", "studied"],
["researching", "studying"],
["resemblance", "similarity"],
["resemble", "look like"],
["resembled", "looked like"],
["resembled", "was like"],
["resembles", "looks like"],
["resembles", "is like"],
["resembling", "looking like"],
["reset", "restart"],
["resetting", "restarting"],
["reside", "live"],
["reside", "live"],
["resided", "lived"],
["resided", "lived"],
["residing", "living"],
["residing", "living"],
["resign", "leave"],
["resigned", "left"],
["resilient", "strong"],
["respond", "answer"],
["responded", "answered"],
["retain", "keep"],
["retain", "keep"],
["retained", "kept"],
["retort", "answer"],
["retreating", "getting"],
["retrieve", "get"],
["retrieve", "get"],
["retrieved", "got"],
["retrieved", "got"],
["retrieving", "getting"],
["reveal", "show"],
["revealed", "showed"],
["revere", "respect"],
["revered", "respected"],
["reverence", "respect"],
["revise", "change"],
["revised", "changed"],
["revising", "changing"],
["revision", "change"],
["revolting", "terrible"],
["revolving", "turning"],
["ridicule", "make fun of"],
["ridiculed", "made fun of"],
["ridiculing", "making fun of"],
["rife", "rich"],
["rifle", "gun"],
["rigid", "hard"],
["ripple", "small wave"],
["rival", "enemy"],
["rivalled", "competed with"],
["robust", "strong"],
["robustly", "strongly"],
["rotate", "turn"],
["rouse", "excite"],
["route", "path"],
["rsvp", "respond"],
["rudimentary", "basic"],
["rumor", "story"],
["rumors", "stories"],
["rumour", "story"],
["rumours", "stories"],
["rupture", "break"],
["ruptured", "broke"],
["rupturing", "breaking"],
["sacred", "important"],
["salivate", "drool"],
["salivated", "drooled"],
["salivating", "drooling"],
["sanctified", "important"],
["satisfying", "good"],
["satisfying", "nice"],
["scheme", "plan"],
["scorch", "burn"],
["scorches", "burns"],
["scour", "search"],
["scoured", "searched"],
["scrolled", "rolled"],
["scrolling", "rolling"],
["scrutinize", "criticize"],
["scrutinized", "criticized"],
["scrutinizing", "criticizing"],
["scurried", "ran"],
["scurry", "run"],
["scurrying", "running"],
["section", "part"],
["seek", "search for"],
["segment", "part"],
["segment", "part"],
["segregate", "separate"],
["segregated", "separated"],
["segregating", "separating"],
["seldom", "rarely"],
["select", "choose"],
["selected", "chose"],
["selecting", "choosing"],
["selection", "choice"],
["seminar", "class"],
["sensation", "feeling"],
["sever", "cut"],
["several", "some"],
["severe", "serious"],
["severed", "cut"],
["severely", "seriously"],
["severing", "cutting"],
["shall", "will"],
["shall", "will"],
["shameful", "bad"],
["shatter", "break"],
["shattered", "broke"],
["shattering", "breaking"],
["shifted", "moved"],
["shifting", "moved"],
["shifting", "moving"],
["shifting", "moving"],
["shimmered", "danced"],
["shimmering", "dancing"],
["shiny", "bright"],
["shoddy", "poor"],
["shouldâve", "should have"],
["shouldn't", "should not"],
["shout", "yell"],
["shouted", "yelled"],
["shouting", "yelling"],
["shove", "push"],
["shoved", "pushed"],
["shoving", "pushing"],
["shredded", "ripped"],
["shredding", "ripping"],
["shrivel", "shrink"],
["shrivelling", "shrinking"],
["shrivelled", "shrunk"],
["shutting", "closing"],
["silent", "quiet"],
["sillier", "funnier"],
["silliest", "funniest"],
["silly", "funny"],
["similarly", "also"],
["simmer", "boil"],
["simmered", "boiled"],
["simmering", "boiling"],
["simultaneously", "at the same time"],
["sinful", "bad"],
["singe", "burn"],
["situate", "place"],
["situated", "placed"],
["situating", "placing"],
["sixtieth", "60th"],
["sizable", "big"],
["skidded", "slipped"],
["skidding", "slipping"],
["skill", "ability"],
["skilled", "good"],
["skillful"],
["skinny", "thin"],
["slain", "killed"],
["slam", "hit"],
["slaughtered", "killed"],
["slaughtering", "killing"],
["slay", "kill"],
["slayer", "killer"],
["slaying", "killing"],
["sliced", "cut"],
["slicing", "cutting"],
["slid", "slipped"],
["slides", "slips"],
["sliding", "slipping"],
["slight", "small"],
["slighted", "hurt"],
["slightest", "smallest"],
["slipped", "fell"],
["slipping", "falling"],
["slumber", "sleep"],
["slumbered", "slept"],
["slumbering", "sleeping"],
["slumbers", "sleeps"],
["smacked", "hit"],
["smacking", "hitting"],
["smash", "hit"],
["smirk", "smile"],
["smirked", "smiled"],
["smuggle", "sneak"],
["smuggled", "snook"],
["smuggling", "sneaking"],
["snicker", "laugh"],
["snickered", "laughed"],
["snickering", "laughing"],
["snip", "cut"],
["snooze", "sleep"],
["snoozed", "slept"],
["snoozing", "sleeping"],
["snout", "nose"],
["snug", "comfortable"],
["snug", "tight"],
["soar", "fly"],
["soared", "flew"],
["soaring", "flying"],
["sobbed", "cried"],
["sobbing", "crying"],
["sofa", "couch"],
["solemn", "serious"],
["solicitous", "respectful"],
["somber", "serious"],
["sore", "painful"],
["sorority", "club"],
["sorrow", "sadness"],
["spawned", "created"],
["speak", "talk"],
["speaker", "talker"],
["speaking", "talking"],
["specialist", "expert"],
["specifies", "decides"],
["specifying", "deciding"],
["specimen", "example"],
["spectacular", "amazing"],
["spectacularly", "amazingly"],
["spectacularly", "very"],
["speculate", "guess"],
["speculated", "guessed"],
["spinning", "turning"],
["spiraled", "twisted"],
["spiraling", "twisting"],
["spiralled", "twisted"],
["spiralling", "twisting"],
["spoke", "talked"],
["spoken", "said"],
["sprain", "twist"],
["sprained", "twisted"],
["spraining", "twisting"],
["spun", "turned"],
["squad", "team"],
["stale", "old"],
["stated", "said"],
["stating", "saying"],
["stimulate", "excite"],
["stimulated", "excited"],
["stipulate", "saying"],
["stipulated", "said"],
["stipulates", "says"],
["stipulating", "saying"],
["stored", "kept"],
["storing", "keeping"],
["strenuous", "hard"],
["struggle", "fight"],
["struggled", "fought"],
["struggling", "fighting"],
["subsequent", "following"],
["subsequently", "consequently"],
["subsequently", "after"],
["subset", "part"],
["substantiate", "support"],
["substituting", "switching"],
["subterranean", "underground"],
["suitable", "ok"],
["suitable", "ok"],
["superficial", "cheap"],
["superficially", "lightly"],
["superfluous", "unnecessary"],
["superfluous", "unnecessary"],
["superfluously", "unnecessarily"],
["supper", "dinner"],
["supplementary", "extra"],
["supplied", "brought"],
["supplying", "bringing"],
["suppose", "guess"],
["suppose", "guess"],
["supposing", "assuming"],
["supposing", "if"],
["supreme", "best"],
["surname", "family name"],
["swap", "trade"],
["swapped", "traded"],
["swapping", "trading"],
["switching", "changing"],
["synergize", "combine"],
["synopsis", "summary"],
["tactful", "respectful"],
["tactic", "idea"],
["tale", "story"],
["tame", "kind"],
["tantalize", "excite"],
["tantalized", "excited"],
["tantalizing", "exciting"],
["tardy", "late"],
["task", "job"],
["task", "job"],
["tavern", "bar"],
["tempo", "speed"],
["tenderize", "soften"],
["tenderized", "softened"],
["tenderizing", "softening"],
["tenet", "belief"],
["tenuous", "unsure"],
["terminate", "end"],
["terminated", "ended"],
["terminating", "ending"],
["terrific", "great"],
["terrified", "scared"],
["terrify", "scare"],
["terrifying", "scaring"],
["terse", "short"],
["tertiary", "third"],
["testimony", "statement"],
["texture", "feeling"],
["theories", "ideas"],
["theory", "idea"],
["thereafter", "from that time on"],
["therefore", "so"],
["thief", "robber"],
["thievery", "robbery"],
["thieves", "robbers"],
["thirtieth", "30th"],
["tho", "though"],
["thorough", "complete"],
["thoroughly", "completely"],
["thoughtful", "respectful"],
["thrive", "live well"],
["thrived", "lived well"],
["thriving", "living well"],
["throughout", "during"],
["thus", "so"],
["thwack", "hit"],
["tidied", "cleaned"],
["tidier", "cleaner"],
["tidy", "clean"],
["tidying", "cleaning"],
["timid", "shy"],
["timid", "shy"],
["tiniest", "littlest"],
["tinker", "play"],
["tinker", "play"],
["tinkered", "played"],
["tinkered", "played"],
["tinkering", "playing"],
["tiny", "little"],
["tires", "wheels"],
["title", "name"],
["titled", "named"],
["toss", "throw"],
["tossed", "threw"],
["town", "city"],
["tracked", "followed"],
["tracking", "following"],
["trail", "path"],
["trailing", "following"],
["tranquil", "quiet"],
["transferred", "moved"],
["transferring", "moving"],
["transform", "change"],
["transformed", "changed"],
["transforming", "changing"],
["transition", "change"],
["transmission", "message"],
["transmit", "send"],
["transmitted", "sent"],
["transmitting", "sending"],
["transparent", "clear"],
["trash", "garbage"],
["trashed", "destroyed"],
["treacherous", "difficult"],
["treacherous", "dangerous"],
["treatise", "book"],
["treaty", "agreement"],
["trekking", "travelling"],
["tremendous", "great"],
["tremendously", "greatly"],
["tremor", "shaking"],
["tremors", "shaking"],
["trendy", "popular"],
["triggered", "started"],
["triggering", "starting"],
["triggers", "starts"],
["triumph", "success"],
["triumphant", "successful"],
["triumphantly", "successfully"],
["trivial", "unimportant"],
["tugged", "pulled"],
["tugging", "pulling"],
["turbulent", "shaky"],
["turmoil", "trouble"],
["turmoil", "trouble"],
["turnout", "crowd"],
["tussle", "fight"],
["tussled", "fought"],
["tussling", "fighting"],
["ultimate", "best"],
["unambiguous", "clear"],
["unambiguous", "clear"],
["unambiguously", "clearly"],
["unbearable", "not ok"],
["uncanny", "weird"],
["undeniable", "sure"],
["undeniably", "surely"],
["undergarment", "underwear"],
["undergo", "do"],
["undergoing", "doing"],
["underlies", "is under"],
["underwent", "did"],
["undesirable", "unwanted"],
["unemployed", "jobless"],
["unemployment", "joblessness"],
["unethical", "bad"],
["unexpressible", "unsayable"],
["unfathomable", "amazing"],
["unfavourable", "bad"],
["unfortunately", "unluckily"],
["unilateral", "one-sided"],
["unjust", "wrong"],
["unprepared", "not ready"],
["unrecognized", "unknown"],
["unrelenting", "unending"],
["unsuitable", "wrong"],
["untrue", "wrong"],
["updating", "choosing"],
["upgrading", "improving"],
["upscale", "nice"],
["urban", "city"],
["usage", "use"],
["useful", "helpful"],
["usurp", "take"],
["usurped", "took"],
["usurper", "taker"],
["usurping", "taking"],
["utilization", "use"],
["utilized", "used"],
["utilizes", "uses"],
["utilizing", "using"],
["utopian", "hopefull"],
["vacate", "leave"],
["vacuous", "empty"],
["vague", "unclear"],
["variation", "change"],
["varies", "changes"],
["varies", "changes"],
["varieties", "kinds"],
["varieties", "types"],
["vary", "change"],
["vary", "change"],
["varying", "changing"],
["varying", "changing"],
["vast", "big"],
["vastly", "greatly"],
["veer", "turn"],
["veered", "turned"],
["veering", "turning"],
["vehement", "violent"],
["vehemently", "violently"],
["vehicle", "car"],
["veneration", "respect"],
["ventilated", "aired"],
["vexed", "confused"],
["vexing", "confusing"],
["viable", "possible"],
["vice versa", "the other way round"],
["viewed", "watched"],
["viewer", "watcher"],
["viewing", "watching"],
["violation", "crime"],
["visage", "face"],
["visualize", "see"],
["visualize", "see"],
["visualized", "saw"],
["visualized", "saw"],
["visualizing", "seeing"],
["visualizing", "seeing"],
["vitality", "liveliness"],
["voiced", "said"],
["vowed", "promised"],
["vowing", "promising"],
["voyage", "trip"],
["voyager", "traveler"],
["voyaging", "traveling"],
["vulgar", "gross"],
["wail", "cry"],
["wailed", "cry"],
["wailing", "crying"],
["waist", "middle"],
["wallop", "hit"],
["walloped", "hit"],
["warden", "guard"],
["wardrobe", "clothes"],
["warfare", "war"],
["warped", "bent"],
["warping", "bending"],
["wash", "clean"],
["washer", "cleaner"],
["washing", "cleaning"],
["we'd", "we had"],
["we'll", "we will"],
["we've", "we have"],
["wealthy", "rich"],
["weariness", "tiredness"],
["weary", "tired"],
["wedded", "married"],
["weds", "marries"],
["wee", "small"],
["weeps", "cries"],
["weepy", "not strong"],
["wham", "hit"],
["whatâd", "what did"],
["whatâve", "what have"],
["wheeze", "breathe hard"],
["where'd", "where did"],
["whereas", "but"],
["whereby", "by which"],
["wherewithal", "smarts"],
["whether", "if"],
["whether", "if"],
["whiff", "smell"],
["whilst", "while"],
["whim", "sudden desire"],
["whimper", "cry"],
["whimsical", "not strong"],
["whimsy", "light"],
["wholly", "all"],
["whom", "who"],
["whosoever", "whoever"],
["wildly", "crazily"],
["willing", "ready"],
["wimp", "weak person"],
["wise", "smart"],
["wished", "wanted"],
["wishes", "wants"],
["wishing", "wanting"],
["withdraw", "remove"],
["withdrawing", "removing"],
["withdrew", "removed"],
["witty", "smart"],
["womankind", "all women"],
["wonderful", "great"],
["wonderment", "surprise"],
["wondrous", "good"],
["worried", "scared"],
["worries", "scared"],
["worry", "fear"],
["worrying", "fearing"],
["worthwhile", "important"],
["wouldâve", "would have"],
["wouldn't", "would not"],
["yearn", "desire"],
["yearned", "desired"],
["yearning", "desire"],
["yearnings", "desires"],
["yield", "give"],
["yielded", "gave"],
["yielding", "giving"],
["yonder", "there"],
["you'll", "you will"],
["you'll", "you will"],
["you've", "you have"],
["youthful", "young"],
["youthfully", "young"],
["yup", "yes"],
["zany", "crazy"],
["zenith", "top"],
["zipping", "going quickly"],
["zips", "goes quickly"],
["all ears", "listening carefully"],
["as a last resort", "if everything else fails"],
["as to", "for"],
["at any rate", "anyway"],
["at odds", "in disagreement"],
["at once", "immediately"],
["at the drop of a hat", "immediately"],
["at the top of one's lungs", "with a very loud voice"],
["at times", "sometimes"],
["back and forth", "backwards and forwards"],
["cash cow", "easy way to make money"],
["bargain for", "anticipate"],
["bargained for", "anticipated"],
["barge in on", "to interrupt"],
["bear in mind", "to consider"],
["bear with", "to be patient with"],
["beat around the bush", "to speak indirectly"],
["birthday suit", "completely naked body"],
["black out", "faint"],
["blast off", "shoot into the sky"],
["brand-new", "very new"],
["account for", "explain"],
["all of a sudden", "suddenly"],
["as a matter of fact", "actually"],
["as soon as", "when"],
["hold on", "wait"],
["in case", "if"],
["of course", "certainly"],
["right away", "immediately"],
["show up", "appear"],
["so far", "until now"],
["stick with", "continue"],
["take over", "take control"],
["took over", "took control"],
["take place", "happen"],
["took place", "happened"],
["turned in", "gave"],
["to the teeth", "heavily"],
["was hard up for cash", "had no money"],
["from scratch", "from the beginning"],
["have a cow", "get upset"],
["blow up", "explode"],
["blew up", "exploded"],
["bone up on", "study"],
["brush up on", "improve"],
["called off", "cancelled"],
["cheer up", "become happier"],
["chicken out", "loose the courage"],
["count on", "trust"],
["drag on", "last too long"],
["drop in", "visit"],
["drop by", "visit"],
["dropped out", "left"],
["egg on", "encourage"],
["feel up to", "feel strong enough for"],
["find out", "learn"],
["found out", "learned"],
["get along", "be friends"],
["get down to", "now do"],
["get over with", "end"],
["hand in", "give in"],
["keep on", "continue"],
["laid off", "fired"],
["look after", "take care of"],
["look up", "search for"],
["nod off", "fall asleep"],
["pass away", "die"],
["pass out", "faint"],
["the wild", "nature"],
["weaselled out", "got out"],
["by the wayside", "away"],
["all of a sudden", "immediately"],
["embarked on", "began"],
["refrained from", "avoided"],
["taken for granted", "not appreciated"],
["out of the loop", "not connected"],
["push the envelope", "push the rules"],
["accounted for", "included"],
["passed away", "died"],
["a couple of", "some"],
["spare some", "give some"],
["in opposition to", "against"],
["identical to", "the same as"],
["to and fro", "around"],
["due to", "because of"],
["in order to", "to"],
["in light of", "with"],
["chew out", "tell off"],
["cut it out", "stop"],
["with regard to", "about"],
["by means of", "by"],
["in the event that", "if"],
["until such time", "until"],
["during such time", "while"],
["in respect of", "for"],
["in view of the fact", "because"],
["on the part of", "by"],
["subsequent to", "after"],
["under the provisions of", "under"],
["in lieu", "instead"],
["adjacent to", "beside"],
["by means of", "by"],
["in the near future", "soon"],
["deal with", "handle"],
["a few", "some"],
["pretty much", "almost"],
["what matters", "what's important"],
["on duty", "working"],
["for instance", "for example"],
["attached to", "put the"],
["as to", "about"],
["get go", " beginning"],
["don't mention it", "it's ok"],
["go bad", "become bad"],
["goes bad", "becomes bad"],
["make amends", "become friends"],
["prior to", "before"],
["enrolled in", "entered"],
["enrol in", "enter"],
["pet peeve", "most unknowing thing"],
["as a precaution", "for safety"],
["prey on", "eat"],
["preyed on", "ate"],
["praise on", "eats"],
["preying on", "eating"],
["one another", "each other"],
["in retrospect â looking back"],
["just slightly â just a little"],
["come about", "happen"],
["come to a stop -stop"],
["come to a stop -stop"],
["came to a stop -stopped"],
["coming to a stop -stopping"],
["come to an agreement", "agree"],
["came to an agreement", "agreed"],
["gave her word", "promised"],
["gave his word", "promised"],
["gave your word", "promised"],
["had a talk", "talked"],
["have a talk", "talk"],
["let down", "disappoint"],
["take into account", "include"],
["taken into account", "included"],
["in the right", "right"],
["in the wrong", "wrong"],
["in the name of", "for"],
["in motion", "moving"],
["of use", "helpful"],
["of no use", "not helpful"],
["blew up", "exploded"],
["non compliant", "disagreeable"],
["a great deal more", "a lot more"],
["a great deal less", "a lot less"],
["figure out", "learn"],
["figured out", "learned"],
["out of date", "old"],
["deal with", "handle"],
["a few", "some"],
["pretty much", "almost"],
["what matters", "what's important"],
["on duty", "working"],
["for instance", "for example"],
["attached to", "put the"],
["as to", "about"],
["hands down", "definitely"],
["taken aback", "surprised"],
["on awful lot", "a lot"],
["such time", "the time"],
["such a time", "the time"],
["due time", "some time"],
["responding to", "answering"],
["responded to", "answered"],
["child's play", "easy"],
["childs play", "easy"],
["rather than", "instead of"],
["partake in", "do"],
["pull through", "survive"],
["track down", "find"],
["full blastâtop speed"],
["pipe down", "quiet"],
["pined for", "missed"],
["pining for", "missing"],
["pine for", "miss"],
["in a pinch", "in an emergency"],
["aversion to", "dislike of"],
["pertained to", "involved"],
["pertaining to", "involving"],
["pertain to", "involve"],
["a nuisance", "annoying"],
["per seâreally"],
["preferred to", "liked to"],
["preferring to", "liking to"],
["prefer to", "like to"],
["sexual intercourse", "sex"],
["dawn on", "come to"],
["down in the dumps", "sad"],
["be obliged to", "be happy to"],
["doze off", "fall asleep"],
["nooks and crannies", "small parts"],
["adjacent to", "aside"],
["adverse to", "against"],
["opposed to", "against"],
["sought after", "look for"],
["prey on", "eat"],
["preyed on", "ate"],
["preys on", "eats"],
["preying on", "eating"],
["bona fide", "real"],
["bear the burden", "have the trouble"],
["the gross majority", "most"],
["the majority of", "most of"],
["scene of the crime", "place of the crime"],
["abide by", "follow"],
["over and over", "many times"],
["abiding by", "following"],
["abided by its", "followed"],
["abides by", "follows"],
["response to", "answer"],
["being facetious", "joking"]
]